class Todo < ApplicationRecord
  # Attributes
  attr_reader id: Integer
  attr_reader title: String
  attr_reader description: String
  attr_reader priority: String
  attr_reader status: String
  attr_reader created_at: Time
  attr_reader updated_at: Time
end
