version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hmvc_and_rbs_development
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: 123123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://todo:123123@db:5432/hmvc_and_rbs_development
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        bundle exec rails db:create db:migrate &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "

  vite:
    build: .
    ports:
      - "3036:3036"
    volumes:
      - .:/app
    command: >
      sh -c "
        yarn install &&
        bundle exec bin/vite dev
      "

volumes:
  db_data:
