class ApplicationOperation
  @params: untyped

  @current_user: untyped

  attr_reader params: untyped

  attr_reader current_user: untyped

  def initialize: (untyped params, ?::Hash[untyped, untyped] data) -> void
end
