default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todos_development
  username: trongtk248
  password: 123123
  host: localhost
  port: 5432

test:
  <<: *default
  database: todos_test
  username: trongtk248
  password: 123123
  host: localhost
  port: 5432

production:
  <<: *default
  database: todos_production
