default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "todos_development" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

staging:
  primary:
    <<: *default
    database: todos_staging
    username: postgres_staging
    password: staging
    host: localhost
    port: 5432

  cable:
    <<: *default
    database: todos_staging
    username: postgres_staging
    password: staging
    host: localhost
    port: 5432

production:
  primary:
    <<: *default
    database: todos_production
    username: postgres_production
    password: production
    host: localhost
    port: 5432

  cable:
    <<: *default
    database: todos_production
    username: postgres_production
    password: production
    host: localhost
    port: 5432
